### ISSUE TITLE
Shell Script Syntax

### ISSUE THREAD

**Issue by Hayao0819** [CyberShadow/aconfmgr#110]
There are some areas I would like to improve on how to write Bash.
Most of this writing is done according to Google's guidelines.
It's impossible to follow everything completely, but there are places where it can be improved.

- Use {} for variable names and quote the entire path
  Example: [main.sh L8](https://github.com/CyberShadow/aconfmgr/blob/6f879b5516a2ff7011dd21f16b5345162fc257b1/src/main.bash#L8)

```bash
# Original code
source "$src_dir"/common.bash

# Fixed code
source "${srcdir}/common.bash"
```

- `then` and `do ` should be written in one line
- Use arithmetic expansion for numerical comparison
  Example: [main.sh L65](https://github.com/CyberShadow/aconfmgr/blob/6f879b5516a2ff7011dd21f16b5345162fc257b1/src/main.bash#L65)

```bash
# Original code
while [[ $# != 0 ]]
do

# Fixed code
while (( "${#}" != 0 )); do
```

If you agree with this change, I will make a pull request to make these changes.
I don't do all the replacements at once because it's a major change.
Start with a script that has fewer lines and less impact.
These changes increase the readability of the source code and reduce redundancy.

**Comment by CyberShadow** [comment]
I don't see how any of the items in this list are improvements; they seem to be simply different stylistic choices. I think the first and the third in particular makes the code harder to read, not easier, by using more syntax than before.

The `!=` in `while [[ $# != 0 ]]` should be `-ne`, though.

Here is my personal TODO list for some things which I would consider actual improvements in shell syntax related matters:

- Correctness fixes [0/8]
  - [ ] Flags
    - [ ] Add `set -e` atop all functions called via $(...)
    - [X] ~~Add `eval "$AconfFuncPrologue"` which sets flags (set -eu) and traps (`trap 'OnError EXIT ERR`)~~
    - [ ] Add prologue anyway. Do `set -e` and check for CMD_IGNORE_RETURN when inside the test suite
    - [X] Enable `set -o errtrace`
    - [ ] inherit_errexit
  - [ ] Replace test -d, -h, -f etc. with stat? (Distinguish "not a X" result from errors)
  - [ ] Use `command -v` instead of `which`
  - [ ] `printf --`
  - [ ] Review process substitutions e.g. <(pacman ...) for exit code handling
  - [ ] Review command substitutions e.g. $(...), they also don't stop executing when in another command
  - [ ] Review uses of 'read' to use correct IFS (otherwise it strips IFS chars from beginning/end)
  - [ ] Ensure config directory (and tmp directory?) are not world-readable
- Code cleanup [0/27]
  - [ ] Remove `\` from `| \`, `|| \`, etc. (`\` as line continuation character unnecessary if it's implied by pipe or boolean expression OSLT)
  - [ ] Replace `shift` with `"${@:2}"` etc.
  - [ ] Replace `var=$(printf ..)` with `printf -v`
  - [ ] Replace `eval` (to unescape) with `printf %b` ?
  - [ ] Replace `/dev/stdin` with -
  - [ ] Replace `PrintArray foo` with `PrintArray "${foo[@]}"`
  - [ ] Replace `$line =` ^(.*)\	(.*)\	(.*)$` with IFS=$'\t' read ...
  - [ ] Replace y/n values for "boolean" variables with true/false
    - [ ] `((verbose))`
  - [ ] Replace 0-array helpers with initializing arrays with ()
    - [ ] Add bash feature check, as this requires Bash 4.4: https://stackoverflow.com/a/39687362/21501
  - [ ] Replace `printf "%s" "$var" | cmd` with `cmd <<< "$var"` ?
  - [ ] Use `FatalError` instead of `Log/Exit 1`
  - [ ] Remove `PrintFileProps`
  - [ ] `( ... ) < foo` -> `{ ... ; } < foo` (don't need subshell for redirects)
  - [ ] `( ... )` -> `{ ... ; }` in general where applicable (don't need subshells for a lot of things)
  - [ ] Use semantic color functions (path, number, package, etc.) instead of the colors themselves
  - [ ] Delete ": # include in coverage"
  - [ ] No error handling in cmd "$(...)" (replace with local var;var=$(...);cmd "$var")
  - [ ] No error handling in cmd <(...) (replace with SubC cmd <(SubS ...) and set/check error status in SubS/SubC)
  - [ ] Add `test -v` before `eval` of var name
  - [ ] Use fds instead of >> in a loop
  - [ ] Review use of `==` / `!=` with numerical values

I may accept patches which improve on the above.

**Comment by Hayao0819** [comment]
Most of them are  different stylistic choices.
However, as Google has stated, those changes (at least writing do and then in one line) improve the readability of the source code.

**Comment by CyberShadow** [comment]
Well, that is only the opinion of the author of the style guide.

It is common for companies to standardize on some particular style, because consistency is more important than readability. For example, in case of variable syntax, `${x}` can be used in more places than `$x` (because you can't write `${x}foo` in the other way). Ergo, from a consistency point of view, it makes more sense to use braces everywhere than to not use braces anywhere, so they chose to use braces everywhere. (Note that there is still a way to write this expression without braces: `"$x"foo`.)

I believe that particular style guide was created some number of years ago. The syntactic load of languages is increasingly more apparent, and recent trends in programming languages prefer languages with less syntax (see e.g. Go and Rust shedding C's required parens for `if` expressions). So, I don't think that adding more syntax makes things more readable, unless the syntax has some vital role like prevent ambiguity. Good syntax highlighting fills this role much more effectively (and I would consider any advice to not rely on syntax highlighting these days to be severely outdated).
