### ISSUE TITLE
documentation for IgnorePath syntax

### ISSUE THREAD

**Issue by Dieterbe** [CyberShadow/aconfmgr#122]
Hello,
i couldn't find the exact required syntax for IgnorePath.
#78 demonstrates this perfectly, quote:

> The correct syntax would be IgnorePath '/etc/docker/*'.
> (IgnorePath '/etc/docker' will also work, but only in certain circumstances, and is not recommended.)
> IgnorePath '/etc/docker/' will not work, as you have observed.

to the reader/user, this isn't really clear. What are the rules? How will the patterns be interpreted? I was reading the source code for `AconfCreateFindIgnoreArgs` which says something about using them as find arguments but also (in certain cases) turning shell globbing strings into regular expressions. (i notice a sed rule that replaces `*` by `.*`)
So, what are the guidelines, as a user, on how to form the rules?
Whenever we want to ignore a directory and its contents, should we always use `/path/to/directory/*`? When is any other form appropriate?

**Comment by CyberShadow** [comment]
Here is what the helper's documentation says:

https://github.com/CyberShadow/aconfmgr/blob/7acbdd330d9a81846d28c93d81dd1094c26123b5/src/helpers.bash#L325

This is as far as the public aspect of the semantics goes, because, as you've noticed, the implementation gets a little hairy. It is used as an argument to `find -wholename`, and also in a bash `==` expression. I think they use the same glibc function to match the pattern against file names, but we're not really in a position to make any guarantees about it.

That e.g. `IgnorePath '/etc/docker'` works to ignore a single directory and its contents is more of an emergent quirk of the implementation details; though, it is also valid if you want to indicate that you want to ignore the properties of a directory (but not its children), if that directory is owned by some package.

The regular expression manipulation is part of a nice optimization contributed in #74, and hopefully should be fully transparent to users.

**Comment by CyberShadow** [comment]
I hope that answered the question!
