### ISSUE TITLE
[Bug]: Changed file duplicates `CopyFile` in 99-unsorted

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#141]
### General description of the problem:

When a file with an existing `CopyFile` declaration in the config is changes, and `aconfmgr save` run, the change is reflected in `files/`, but additionally a `CopyFile` line is added to `99-unsorted.sh` as though it did not already exist in the configuration.

### Steps to reproduce the problem:

1. `aconfmgr save`
1. `echo 'CopyFile /tmp/test' > "$XDG_CONFIG_HOME/aconfmgr/99-test.sh"`
1. `mkdir -p "$XDG_CONFIG_HOME/aconfmgr/files/tmp" && touch "$XDG_CONFIG_HOME/aconfmgr/files/tmp/test"`
1. `aconfmgr apply`
1. `echo test123 > /tmp/test`
1. `aconfmgr save`

### Expected result:

1. `files/tmp/test` contents updated to `test123`
1. `99-unsorted.sh` unchanged

### Actual result:

1. `files/tmp/test` contents updated to `test123`
1. `99-unsorted.sh` appended with `CopyFile /tmp/test`

**Comment by CyberShadow** [comment]
Not a bug - the added calls are a necessary redundancy emergent from the user's configuration being free-form. aconfmgr does not know that the previous copy was created via a `CreateFile` call, and even if it did, it would have no way of knowing that the staged file contents has not been modified via another mechanism since that call, allowing it to be safely reused.

So, an annoyance to be sure, but not fixable in a provably correct way without either undermining some of the design's guarantees or doing something very expensive like re-evaluating the entire configuration up to that point to check whether the `CopyFile` call is needed.

**Comment by OJFord** [comment]
👍🏻 Understood.
