### ISSUE TITLE
Cleanup of files directory

### ISSUE THREAD

**Issue by nightbluepn** [CyberShadow/aconfmgr#21]
The files directory never seems to be cleaned up, for instance if i "aconfmgr save", then ignore some files that were found and added to 99-unsorted.sh as "CopyFile ...", these files will stay in the files directory even though they are ignored.
Is this the expected behaviour and what could i do to only keep the files which actually exist in the configuration?

**Comment by CyberShadow** [comment]
I've thought about this as well. At some point I tried to add a warning to identify files that were not being used, however this results in false positives when the files are only referenced conditionally (e.g. on some hostnames). I haven't thought of a satisfying way to make it possible to indicate which files are still used despite CopyFile not being invoked for them.

I've now added that warning in b589c0a9674d41cee5c973f1217da0664718d098, however it is only displayed when running the new "check" action. Because it can have false positives, you can think of it as a kind of linting.

> what could i do to only keep the files which actually exist in the configuration?

Alternatively, this can be achieved by simple diligence: ensure that whenever you add a `CopyFile` line to your configuration scripts, so is the file, and more importantly, when removing `CopyFile` directives, to remove the corresponding files as well. Then, if your configuration is under version control, `git status` should show any remaining files added by `aconfmgr save` that you haven't dealt with. I accept that this is not a practical recommendation, though.

**Comment by nightbluepn** [comment]
The linting already helps me out perfectly, thank you.

Another suggestion: what if one could delete the whole files folder, and then run 'aconfmgr save' such that it will not check whether the file in 'files' and the file on the system are different, but to just copy every file from the system, as it does when it finds an unknown file.
This way, one could just throw away the 'files' folder and rebuild it.

**Comment by CyberShadow** [comment]
I suppose that would be an option, but I'm not sure about implementing it in aconfmgr directly, because it complicates the semantics of the `CopyFile` helper function. Right now its contract is that it expects the source file to exist, but this change would make it OK for it to not exist sometimes, or something like that.

I think the same could be achieved manually:
1. Comment out all `CopyFile` invocations in your configuration, e.g. using `sed -i s/CopyFile/#CopyFile/g *.sh`, or redefine `CopyFile` to be a no-op stub
2. Delete the `files/` directory
3. Run `aconfmgr save`
4. Discard the newly-added `CopyFile` directives to `99-unsorted.sh`
5. Undo the changes done in step 1
6. See if your configuration still works.

This would additionally check that there are no redundant `CopyFile` invocations in your configuration scripts.

**Comment by nightbluepn** [comment]
Yeah, that is actually an easier way, thanks for pointing it out. Feel free to close this!
