### ISSUE TITLE
AddPackageGroup

### ISSUE THREAD

**Issue by jeremejevs** [CyberShadow/aconfmgr#29]
On the first run, I've noticed that I have quite a few `AddPackage` entries that belong to `base` and `base-devel`. I believe it would be a quality of life improvement if there were an `AddPackageGroup`. For now, I just dumped `base` and `base-devel` as a list of ignored packages (I'm installing them as a part of the `pacstrap` command anyway).

In the future, maybe there could also be automatic group detection when doing a save. Until then, maybe `save` could just add this to `99-unsorted`:

```bash
# There's a high chance you may want to uncomment these:

# AddPackageGroup base
# AddPackageGroup base-devel
```

I understand that groups can change, which kills the idempotence. Some package you depend on may get excluded, and you'll be left with a broken script or something of sorts. However, IMO, the added brevity/clarity is appealing, and `aconfmgr` isn't perfectly idempotent as-is anyway, since without version pinning, something that's saved today may get applied as something completely else tomorrow (say, a major update of some package provides a different set of executables). There could also be a warning printed, when some package disappears from a group, after doing an `apply` (that requires some state though, to keep track of what's in each group).

**Comment by CyberShadow** [comment]
Hmm, that would not be how I would do things.

- Many of the packages from the groups are likely dependencies of other packages in your configuration. Try leaving just the programs you use directly, and let aconfmgr unpin / remove everything else - I think you'll find it will remove packages you don't use and leave the necessary packages.

- Is the full set of packages in the group actually needed? Some things is the `base` group are going to be rarely used on most installs, such as `xfsprogs`. I do have that package installed, but only because it's pulled in as a dependency by some software I actively use.

- As an aside, that doesn't sound like a good use case for ignoring packages. `IgnorePackage` is best used when you don't care if a package should or shouldn't be installed. One effect of this is that restoring a configuration on a new machine may result in a broken system due to missing packages. If you're adding the packages to your configuration anyway, you might as well list them explicitly (with `AddPackage`).

The only situation I can think of where there is a good reason to import the entire group is when there is a formal contractual dependency on it, i.e. some documentation saying "to do X, you must have group Y installed". I know that's the case for AUR packages (the contract is that `base-devel` is expected to be installed, thus its members don't need to be listed as build dependencies). So, that would be one reason to add the helper.

In any case, implementing it is simple enough:

```bash
function AddPackageGroup() {
    local group=$1

    for p in $(pacman -Qqg "$group")
    do
        AddPackage "$p"
    done
}
```

Should I add it?

**Comment by jeremejevs** [comment]
> Many of the packages from the groups are likely dependencies of other packages in your configuration. Try leaving just the programs you use directly, and let aconfmgr unpin / remove everything else - I think you'll find it will remove packages you don't use and leave the necessary packages.

In the case of `base` and `base-devel`, it's likely that there are packages that aren't a dependency of anything, but are still used. For example, `tar` is required only by one package, `libtool`. Without `base-devel`, which `libtool` comes with, I'd have no `tar` on my system. Or `sed`, which is required only by `docbook-xsl` and `fakeroot`.

Not many packages to remember to keep, but easier to just write down the groups and not worry.

> Some things is the base group are going to be rarely used on most installs, such as `xfsprogs`.

I think I'm okay with paying this price. Of course, this is subjective, but I would wager that very select few out there don't have the whole `base` group installed.

> As an aside, that doesn't sound like a good use case for ignoring packages.

Yes, I understand that, I'm basically trading 10 lines for 100. My initial package list was a tad intimidating though, so I have decided to exclude `base` and `base-devel`, to make it slightly more approachable.

> The only situation I can think of where there is a good reason to import the entire group is when there is a formal contractual dependency on it, i.e. some documentation saying "to do X, you must have group Y installed".

Yes, I agree, there probably is no need beyond the two bases. Maybe even just have hardcoded `AddBasePackageGroup` and `AddBaseDevelPackageGroup` instead of `AddPackageGroup`, as to discourage potential footguns.

> Should I add it?

Yes, if you agree with it being a core feature. I don't mind using your snippet locally otherwise (thanks for whipping it up, by the way).

**Comment by AndreaOrru** [comment]
I would love this feature. What would be really great is the ability to install a group *except* some set of packages. Is that something we could add to the core features? Happy to do a PR.

**Comment by AndreaOrru** [comment]
> Yes, I agree. Probably there's even no need beyond the two bases. 
I disagree. It's pretty useful with i.e. Gnome.

**Comment by CyberShadow** [comment]
> But anyway, I would love this feature.

If you don't mind, I would like to understand the use case. I can think of the following:

- Make the configuration file tidier
- Ensure that all programs in the group are readily installed (even if you will never need some of them)
- Something else I missed?

**Comment by AndreaOrru** [comment]
It makes the configuration file tidier, for sure.

Also, I feel like is desirable, especially for some groups like `xorg` and `gnome`, to ensure that all the programs in the group are installed. If Gnome gets updated to i.e. version 3.32, and new packages become part of the standard distribution (or conversely, they are not part of it anymore), I'd want them to be included unless explicitly stated (by `RemovePackage`-ing them).

**Comment by CyberShadow** [comment]
> Also, I feel like is desirable, especially for some groups like `xorg` and `gnome`, to ensure that all the programs in the group are installed.

Understood. But, what final goal does this goal serve? I can't think of any situations where it's important that all packages in a group are installed, other than the contractual/documentation one mentioned above. Especially since you mentioned that new additions to a group are included. Is it purely a conceptual one (being able to say "I want to install Gnome" in aconfmgr's configuration)?

**Comment by CyberShadow** [comment]
Thanks, that makes sense - especially the `xorg` fonts example. As I understood it, the idea is like a subscription channel for new software, the membership of which in a group may change according to some external rules.

That's not how I'd do things personally (as one of the goals of my personal configuration is to not have software installed which I don't use), but I understand the use case.

**Comment by CyberShadow** [comment]
The helper was added in https://github.com/CyberShadow/aconfmgr/pull/32.
