### ISSUE TITLE
Document high-level 'how it works' / is a new install and immediate `save` necessary

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#52]
I was trying to figure out how this works, and in particular if it needed to store somewhere a checksum of all files on the system, and so should really be first run on a fresh install.

From looking at the code, it seems not, because it can grab a file list and MD5s from pacman. Nice. But does this mean there are some files that might concievably be changed, but aren't captured in any packages' listing? Or is `base` (and in particular it looks like `filesystem`) a complete listing?

Relatedly, I noticed a PR for upgrading `base` dependency - is it always required to keep `base` and `aconfmgr` in sync, i.e. does every release of `base` necessitate an `aconfmgr` release?

**Comment by CyberShadow** [comment]
> But does this mean there are some files that might concievably be changed, but aren't captured in any packages' listing?

I don't understand this question. Perhaps it is coming from a misunderstanding of how files and packages interact on Arch Linux. Files on the filesystem are either owned by an installed package, or are "orphan" files (created by software generally after installation, as part of its normal function). Because orphan files do not have some well-defined initial state, there is no meaningful way to say whether they've "changed" or not.

Unless ignored, aconfmgr includes changed packages' files and orphan files in the configuration.

> Relatedly, I noticed a PR for upgrading `base` dependency - is it always required to keep `base` and `aconfmgr` in sync, i.e. does every release of `base` necessitate an `aconfmgr` release?

The PR is for automatically updating the release of the Arch Linux filesystem bootstrap tarball that the aconfmgr test suite runs against. It is unrelated to the "base" package group in Arch Linux's package repositories.

**Comment by OJFord** [comment]
Thanks!

> Perhaps it is coming from a misunderstanding of how files and packages interact on Arch Linux.

Most probably; at the very least an incomplete understanding.

> Files on the filesystem are either owned by an installed package, or are "orphan" files (created by software generally after installation, as part of its normal function). [...]  aconfmgr includes changed packages' files and orphan files in the configuration.

Well, that sounds perfect.

Thanks for replying so quickly, and many thanks for providing aconfmgr! I'm looking forward to replacing my own forever bit-rotted and never-working-first-time-when-I-have-a-fresh-system scripts with it, seems exactly what I've been after. Cheers.
