### ISSUE TITLE
Alternative aconfmgr directory?

### ISSUE THREAD

**Issue by mxmilkiib** [CyberShadow/aconfmgr#57]
My home partition is low on space and runs out of it when I run a save and files are copied to files/. I have space on my /var partition though. I could setup a symlink and set some permissions, but might there be a cleaner way to achieve this? Thanks!

**Comment by mxmilkb** [comment]
So I got it working with (I believe) just;
```
sudo mkdir /var/aconfmgr && cd /var/aconfmgr
sudo stow aconfmgr -d /home/milk/sync/dotfiles -t .
sudo TMPDIR=/var/aconfmgr/tmp aconfmgr save -c /var/aconfmgr
```
with the envar as my tmpfs ran out of space.

Potentially a better syntax could be something like;
```
TMPDIR=/var/aconfmgr/tmp FILESDIR=/var/aconfmgr/files aconfmgr save
```
(with the appropriate internal sudos to make missing dirs etc)?

**Comment by CyberShadow** [comment]
aconfmgr always writes configuration files (incl. files copied from the system into the configuration) as the current user, so you would need to either make `/var/aconfmgr` owned (or writable) by you, or run `aconfmgr` as root.

Adding a way to set aconfmgr directory locations through the environment is a possibility, though.

**Comment by CyberShadow** [comment]
Let's revisit this if a symlink or a wrapper / alias proves to be insufficient.

FWIW, as a point of comparison - my personal configuration is under 500KB in size. Large binary files can't usually be described as being part of a system's *configuration*, and other large files are often better patched instead of being included in entirety (which also makes porting modifications to future versions easier). (But, of course, just because someone is using a tool in a different way, doesn't make their use case less valid.)
