### ISSUE TITLE
use multiple file directory and be able to set them

### ISSUE THREAD

**Issue by Alkeryn** [CyberShadow/aconfmgr#63]
So let's say i have many computer that share configuration but also have specific things to each one of them
wouldn't it be easier to have
files-laptop/ #files specific to laptop
files-desktop/ #files specific to desktop
files-server/ #files specific to server
files-shared/ #files shared between all of them
etc... 
?
well being able to set it up that way would be nice ^

**Comment by CyberShadow** [comment]
What is preventing you from doing that?

**Comment by Alkeryn** [comment]
By that i meant having a set flag, by default aconfmgr will use the file/ folder
and i'm asking if there is an option to change that folder upon specific conditions ?

**Comment by CyberShadow** [comment]
Okay, so you would like to have a way to configure `aconfmgr save` to save some files to a different location.

There is currently no option to do that automatically.

**Comment by Alkeryn** [comment]
Yep pretty much rather 
something like
```
$islaptop && SetAdditionalFilesSavePath files-laptop || SetAdditionalFilesSavePath files-desktop
```
but also have it look in the original `files/` for files all computers have in common ^

**Comment by CyberShadow** [comment]
How would `aconfmgr save` decide which directory to put new files in?

**Comment by Alkeryn** [comment]
@CyberShadow I think using a default directory but having a flag such as -d would be the best of both world, then feel free to do it or not :)

**Comment by CyberShadow** [comment]
As far as I understand, you can achieve what you want without any changes in aconfmgr.

- There exists a `CopyFileTo` helper, which allows specifying different source and target paths. This allows copying different files depending on the current system.
- You could also define a custom helper which looks in multiple directories as you described. You could even redefine `CopyFile` to do that, so that the configuration generated by `aconfmgr save` does that by default.
- As for `aconfmgr save`, since it always puts new files in the `files/` directory, you could write an aconfmgr wrapper script which symlinks `config/files` to e.g. `files_$HOSTNAME` before executing aconfmgr.

I think it is worthwhile to make it easier to manage different file versions for different systems, but I'm not sure that the above is necessarily the best way to approach this problem.

**Comment by CyberShadow** [comment]
This area looks like a good topic to develop as a set of third-party helpers; perhaps if an victorious solution with clear benefits emerges, it could be adopted. 

If there is something missing in aconfmgr to allow such helpers to work (e.g. some hooks for saving), that can be filed as separate issues.

Let's continue here: https://github.com/CyberShadow/aconfmgr/wiki
