### ISSUE TITLE
Existing modified files are seen as "New files"

### ISSUE THREAD

**Issue by SeerLite** [CyberShadow/aconfmgr#71]
I'm not sure if this is default behavior. It's kind of annoying because everytime a file is modified/added, I have to check if the file is truly new so I can decide if I can just delete the `CopyFile` entry or I can move it.

Example:
/etc/exists is a file that exists in the system and aconfmgr is configured so that `10-test.sh` has `CopyFile /etc/exists`
Then I modify system's /etc/exists and run `aconfmgr save`
`99-unsorted.sh` now has the following:
```
# current date - New files


CopyFile /etc/exists
```
This gets messy when there's _actual_ new files, since all changes are grouped together.
Is this a bug or intended behavior? If intended, is there a way to not add entries for modified files? It's redundant if they're already listed elsewhere.

Btw, aconfmgr is amazing and I appreciate the work done by CyberShadow on this project. Thank you!

**Comment by CyberShadow** [comment]
> Is this a bug or intended behavior?

It is intended behavior, because aconfmgr doesn't know the mechanism with which your configuration scripts copy the latest version of the file to the output directory. For example, your configuration might be using the `CopyFileTo`, `CreateFile`, or `GetPackageOriginalFile` helpers. Therefore, if a `CreateFile` call is not added, the resulting configuration might not be idempotent.

> If intended, is there a way to not add entries for modified files?

There is no such mechanism, and I can't think of a way of adding one which wouldn't weaken current guarantees. (Checking if `CopyFile` was previously called for that path is not enough, as the result of that call might later be overwritten by a different or custom helper.)

What I personally do is check the git status of the path. If the file was already under version control, this means that it was already installed using `CopyFile`, so the newly-added `CopyFIle` call can be removed; otherwise, it is a new file or it is created through another method, meaning the `CopyFile` call needs to be integrated into the configuration.

If your configuration follows certain conventions (e.g. you use only `CopyFile` or some other fixed set of helpers), you probably could post-process the `99-unsorted.sh` file created by aconfmgr to remove these calls automatically after an `aconfmgr save` invocation.

**Comment by SeerLite** [comment]
I see. This makes it a lot clearer, thanks for explaining! Perhaps changing the header from `New files` to `New/modified files` might make it clearer for future users?
> If your configuration follows certain conventions (e.g. you use only CopyFile or some other fixed set of helpers), you probably could post-process the 99-unsorted.sh file created by aconfmgr to remove these calls automatically after an aconfmgr save invocation.

I think I'll be doing this. A simple script that runs after aconfmgr and checks whether or not I already have the new files set up.

**Comment by SeerLite** [comment]
Oh I had completely forgotten about this issue haha. I see there's new commits about it though, so thank you for making it clearer, I really like this tool.
I guess this can be closed now?

**Comment by Dieterbe** [comment]
I'm really curious how many people would have the idempotency problem. I assume most people just stick with the standard AddPackage/CopyFile directives.
Having to write and run another script after "aconfmgr save" runs, is clunky, but not a huge deal. When i work on this i would also add something to coalesce "AddPackage/RemovePackage" calls. basically the last one wins.

**Comment by CyberShadow** [comment]
A mode in which aconfmgr attempts to patch the existing configuration, instead of always appending to `99-unsorted.sh`, sounds interesting indeed.

**Comment by Dieterbe** [comment]
I've been trying to write a script that traverses all the config sh files, and tries to eliminate redundant calls. (e.g.  multiple AddPackage of the same pkg can be reduced to 1, an AddPackage followed by a RemovePackage can both be removed, etc).
but doing this correctly proved to be too hard to do in pure bash - I could achieve it with a Go or python program, but then it doesn't fit in as well with aconfmgr.
And there's some behaviors that people might disagree on (e.g. duplicate addpackage declarations across multiple .sh files may be desirable for some. and if not desirable, it seems ambiguous which one should be deleted).

**Comment by CyberShadow** [comment]
There is a bit of prior work here:
https://github.com/CyberShadow/aconfmgr/issues/46
