### ISSUE TITLE
Fatal error! when selecting No on remove optional dependencies package prompt

### ISSUE THREAD

**Issue by negativeExponent** [CyberShadow/aconfmgr#82]
As stated in title, fatal error when refusing to remove optional dependency. Everything goes through fine when pressing Y to the prompt
```
checking dependencies...
:: gtk2 optionally requires python2: gtk-builder-convert
:: libnewt optionally requires python2: libnewt support with the _snack module
:: libproxy optionally requires python2: Python 2.x bindings
:: vim optionally requires python2: Python 2 language support

Package (4)     Old Version  Net Change

docbook-xml     4.5-9         -1.96 MiB
libxslt         1.1.34-5      -2.16 MiB
lua-filesystem  1.8.0-1       -0.02 MiB
python2         2.7.18-1     -75.39 MiB

Total Removed Size:  79.54 MiB

:: Do you want to remove these packages? [Y/n] n
:::::: Fatal error! Stack trace:
::::::: /usr/lib/aconfmgr/apply.bash:316 [AconfApply]
::::::: /usr/lib/aconfmgr/main.bash:169 [Main]
::::::: /usr/lib/aconfmgr/main.bash:183 [source]
::::::: /usr/bin/aconfmgr:26 [main]
 negative  aconfmgr  aconfmgr apply
```

**Comment by CyberShadow** [comment]
The prompt comes from `pacman`, and answering no there causes `pacman` to exit with a non-zero status (indicating failure). We don't have a way to know if pacman failed because the user cancelled installation or because of another error. In any case, at best we can show a better error message.

Note that for any prompts that come from aconfmgr itself, pressing `n` results in a different message.

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/aconfmgr/issues/16, if implemented, will allow skipping some steps, but you will need to run aconfmgr with `--paranoid` to make it prompt before invoking `pacman` (it doesn't do so otherwise because `pacman` has its own prompt).
