### ISSUE TITLE
Is there an AddPackage feature for local paths?

### ISSUE THREAD

**Issue by bhigginsuk** [CyberShadow/aconfmgr#97]
I have various PKGBUILD files for my own scripts/packages which aren't on the AUR; I keep them on my machine and sync them with my system configuration.

Currently I ignore the packages and manually build them on a new install. Is there any way, with aconfmgr, to get the AddPackage functionality but from local PKGBUILD files?

**Comment by CyberShadow** [comment]
To answer your question, a feature which works in the exact way you described does not exist in aconfmgr. `aconfmgr` is not very good at building arbitrary packages, which is why it delegates this to AUR helpers as much as possible.

As for the general problem, I can think of two ways to approach this:

1. Ignore the packages using `IgnorePackage`, and install them before or after running `aconfmgr apply`.

2. Place the packages in a pacman repository, and configure it in `pacman.conf`. This repository could be either on a remote machine (so that they are built once and can be installed from anywhere), or on the local machine (i.e. place them there right after building them).

**Comment by bhigginsuk** [comment]
Thank you for the quick response! I thought the feature didn't exist but wanted to ask in case I'd missed it somehow.

Currently I'm doing option 1, but I'll look into creating my own pacman repository, thanks for the tip.

Thank you for creating this tool, it's one of the most valuable components of my setup!
